-- ==============================================================================
-- Oracle Data Guard Primary & Physical Standby Initialization Template
-- Target: Oracle RDBMS 12c / 19c / 23ai
-- ==============================================================================

PROMPT ==============================================================================
PROMPT 1. PRIMARY DATABASE CONFIGURATION (PRODDB)
PROMPT ==============================================================================

-- Enable Force Logging (Mandatory for Data Guard Zero Data Loss)
ALTER DATABASE FORCE LOGGING;

-- Configure Redo Transport Parameters
ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(PRODDB,DR_STANDBY)' SCOPE=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=PRODDB' SCOPE=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=DR_STANDBY ASYNC NOAFFIRM VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=DR_STANDBY' SCOPE=BOTH;
ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_2=ENABLE SCOPE=BOTH;

-- Configure Standby File Management and Role Parameters
ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT=AUTO SCOPE=BOTH;
ALTER SYSTEM SET FAL_SERVER='DR_STANDBY' SCOPE=BOTH;
ALTER SYSTEM SET DG_BROKER_START=TRUE SCOPE=BOTH;

PROMPT ==============================================================================
PROMPT 2. PHYSICAL STANDBY DATABASE CONFIGURATION (DR_STANDBY)
PROMPT ==============================================================================

-- On Standby: Set Database Unique Name & Transport Destination
-- ALTER SYSTEM SET DB_UNIQUE_NAME='DR_STANDBY' SCOPE=SPFILE;
-- ALTER SYSTEM SET LOG_ARCHIVE_CONFIG='DG_CONFIG=(PRODDB,DR_STANDBY)' SCOPE=BOTH;
-- ALTER SYSTEM SET LOG_ARCHIVE_DEST_1='LOCATION=USE_DB_RECOVERY_FILE_DEST VALID_FOR=(ALL_LOGFILES,ALL_ROLES) DB_UNIQUE_NAME=DR_STANDBY' SCOPE=BOTH;
-- ALTER SYSTEM SET LOG_ARCHIVE_DEST_2='SERVICE=PRODDB ASYNC NOAFFIRM VALID_FOR=(ONLINE_LOGFILES,PRIMARY_ROLE) DB_UNIQUE_NAME=PRODDB' SCOPE=BOTH;
-- ALTER SYSTEM SET LOG_ARCHIVE_DEST_STATE_2=ENABLE SCOPE=BOTH;
-- ALTER SYSTEM SET FAL_SERVER='PRODDB' SCOPE=BOTH;
-- ALTER SYSTEM SET STANDBY_FILE_MANAGEMENT=AUTO SCOPE=BOTH;
-- ALTER SYSTEM SET DG_BROKER_START=TRUE SCOPE=BOTH;

-- Start Managed Recovery Process (MRP0) on Standby
-- ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT FROM SESSION;
